### ISSUE TITLE
Short description of the ranking system into the main text

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#101]
It might be a good idea to add a short description of the ranking system (generation of figure 5) also in the main text.

**Comment by ohsOllila** [comment]
I have now updated the caption of figure 5 to describe very roughly the ranking criteria. Maybe this is enough.

**Comment by markussmiettinen** [comment]
I think the caption is good. I have edited it just a bit in my pull request #112. I think we can close this issue.
