### ISSUE TITLE
Figs S7 and S8

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#107]
The legends of these figures claim that Lipid17-jc is plotted with solid blue line. This, however, does not seem to be the case, but either:

1) Lipid-17-jc results exactly match those of CHARMM36 and CHARMM36-UA or
2) The legend has a wrong line type for Lipid-17-jc.

The scripts for producing these figures are not on github, thus I can not check this myself. (I guess the figs were made by @pbuslaev?) In any case, this is rather confusing for the reader, especially because of the possible mix up with the CHARMM36 results.

While fixing this problem, it would be good also to:

1) Adapt the naming of the force fields to match the main text, e.g., CHARMM36UA -> CHARMM36-UA.

2) Use dashed line for CHARMM36-UA, so one sees it though it mostly overlaps with CHARMM36. (Then these two will also look less like a single solid blue line.)

3) Use dotted line for Lipid17-JC, so it is different from the (dashed) Lipid17-ff99.

**Comment by pbuslaev** [comment]
![figS7](https://user-images.githubusercontent.com/10205508/64438357-a0240180-d0d0-11e9-9c7c-4ac64b487dac.png)
![figS8](https://user-images.githubusercontent.com/10205508/64438368-a5814c00-d0d0-11e9-8e05-1c5f8c9e019d.png)

**Comment by pbuslaev** [comment]
Hi! I have changed the figures! Hope they are ok now! I decided to use solid line for Lipid17-jc, hope that is ok.

**Comment by ohsOllila** [comment]
Thanks for the figures, I have now updated the SI.
