### ISSUE TITLE
Figure S2

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#121]
Bottom right panel is missing the red data points. I fixed this in the plotting script for the pull request #120, but could not run the script as the data for PG-containing systems have been moved.

**Comment by ohsOllila** [comment]
This is now fixed in commit https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/f7cf592c17be10d530b610129181a808f53bb400
