### ISSUE TITLE
Table 2

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#129]
- Lipid14/17/Dang with [CaCl2] = 0.13 should have [CaCl2] = 0.12, because 8*55.5/3561=0.1246
- Ref 98 has 24 POPS lipids, thus the corresponding line should have **104:24** instead of 104:26
- Ref 99 has 24 POPS lipids, thus the corresponding line should have **104:24** instead of 104:26
- from @TomPiggot: _GROMOS-CKPM has a superscript d after it but this should be an e._
- Taulukoissa "t_sim" ja "t_anal." ei oo konsistenti (toisessa piste). By Matti per skype.

**Comment by ohsOllila** [comment]
I have now added these into the author_corrections file: https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0
