### ISSUE TITLE
Table 1

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#130]
- from @TomPiggot: both GROMOS-CKP and GROMOS-CKPM need a * for POPS (the DOPS entries correctly have this)
- actually, it might be better to do this as it is done in Table 2, so not have a * in the caption to indicate this, but have a proper footnote, indicated with a letter.
- Taulukoissa "t_sim" ja "t_anal." ei oo konsistenti (toisessa piste). By Matti per skype.

**Comment by ohsOllila** [comment]
I have now added these into the author_corrections file: https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0
