### ISSUE TITLE
Typos in the text

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#131]
- lines 39-40. "The cation binding affinity is, in line with our previous results for PC lipids, not captured correctly by any of the PS force fields." --> "The cation binding affinity is not captured correctly by any of the PS force fields—an observation that is in line with our previous results for PC lipids." Per email from @hsantila.
- line 74. Comma after "phospholipids". Per email from @hsantila.
- lines 139-140. "Figures 1" and "2" should NOT link to the figures 1 and 2 of the present paper, but be just plain text.
- line 150. "Figure 1" should not link to the figure 1 of the present paper, but be just plain text.
- lines 170-171. "1-palmitoyl-2-oleoyl-sn-glycero-3-phospho-L-serine" should be removed, as POPS has been explained already on lines 126-127
- line 212. Remove "the".
- line 220. Break paragraph after the full stop and citation number 39.
- line 266. "phase corrected" --> "phase-corrected"
- lines 322-324. "As was previously observed for PC lipids, 38 also none of the PS models produced a set of SCH values in full quantitative agreement with the experiments." --> "None of the PS models produced a set of SCH values in full quantitative agreement with the experiments—a serious flaw that was also detected in a previous study of PC lipid MD models 38." Proposed per email by @hsantila, @markussmiettinen likes more the original formulation.
- line 343. Should be "bimodal". Per email from Ivan Gushchin.
- line 347. Add the degree symbol after 100.
- lines 423-424. "counterions" --> "monovalent salt"
- line 511. "display" --> "exhibit". Proposed per email by @hsantila.

**Comment by ohsOllila** [comment]
I have now added these into the author_corrections file: https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0
