### ISSUE TITLE
Typos in References.

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#132]
- Ref 31. "PIP2Monolayers" --> "PIP2 Monolayers". Per email by @hsantila.
- Ref 32. "the Complex" --> "The Complex". Per email by @hsantila.
- Ref 71: Ua -> UA. By Matti per skype.
- Ref 80: Ca2+, K+, Cl- ilman yläindeksejä. By Matti per skype.
- Ref 86: "contrations" ja "CaC_2", kävisin ehkä vaihtamassa zenodossa ton nimen ja korjaisin tohon. 117 (Melcr): Ns -> ns." By Matti per skype.

**Comment by ohsOllila** [comment]
I have now added these into the author_corrections file: https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0
