### ISSUE TITLE
Unclarities in the text

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#133]
1. lines 313-316. It is not clear to @markussmiettinen how "the rapid decrease of equilibrium repeat distance with addition of monovalent salt indicates that the hydration levels of multilamellae are sufficiently similar in the reference experiments and our simulations". Could we rephrase to clarify the point?

2. lines 352-353. It is not clear to @markussmiettinen, how one can see from Fig 5B that the dihedral exhibits a "more asymmetric" angle distribution for PS than for PC.

3. lines 370-372. "The force fields studied showed significant differences in both the _binding affinity and the distribution of ions at the interface_." @hsantila asks: Which distribution we are referring to is not clear. Lateral? In z direction?

4. lines 385-388. "The results are consistent with a previous study that suggested the low Apl in PS lipid bilayers to originate from the combination of both the counterion binding and intermolecular interactions between lipid headgroups." @hsantila asks: I'm guessing intermolecular mainly refers to other than electrostatic since ion binding affects that component. Should we specify?

5. lines 422-423. @markussmiettinen proposes to leave out the last sentence of the paragraph. Saying that the behaviour seen here is consistent with what we saw with salt in section S7 seems to somewhat contradict with what we wrote earlier on lines 397-404, i.e., that we do not want to discuss the added salt case, as it is too messy to draw much conclusions.

5.  Lines 470-474. "In all force fields, even the qualitatively correct responses were much exaggerated also in CHARMM36 that underestimated the Ca2+ binding affinity with the sole exception of the larger SCHα , whose change CHARMM36 underestimated." @hsantila points out: This is a very confusing sentence.

6. Lines 516-519. "Importantly, the experimentally measured responses of the PS headgroup SCH to bound calcium, as well as to dilution of the bilayer with zwitterionic PC lipids, were not qualitatively reproduced in any of the tested force fields." @hsantila asks: Didn't we say that C36 is qualitatively correct at rows 471-472?

**Comment by ohsOllila** [comment]
1. lines 313-316: Wuold this be better: "In addition, the equilibrium repeat distance of anionic lipids decreases rapidly with the addition of monovalent salt, 115,116 indicating that the hydration levels of multilamellae are sufficiently similar in the reference experiments and our simulations also in the presence of ions."

2. I will ask to remove the reference to figure 5B from here.

**Comment by markussmiettinen** [comment]
> * lines 313-316: Wuold this be better: "In addition, the equilibrium repeat distance of anionic lipids decreases rapidly with the addition of monovalent salt, 115,116 indicating that the hydration levels of multilamellae are sufficiently similar in the reference experiments and our simulations also in the presence of ions."

So for the case with no added salt we know that the centrifuged and gravimetric samples agree. This we state first, followed then with the sentence under discussion, where we want to say that _even if there is added salt, the simulations should be ok, because the repeat distances in experiments with salt are somewhat similar to what we have in our simulations_.

If this is what we want to say, then the proposed formulation is ok with me.

**Comment by ohsOllila** [comment]
Yes, this is what we want to say.

**Comment by ohsOllila** [comment]
I have now added changes related to these into the author_corrections file (https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0), except 4. and 5. which do not require action in my opinion.

**Comment by markussmiettinen** [comment]
I do not quite agree with the change on lines 468-474 (typoed as 747 in the file).

Current: _In simulations, all of these responses were qualitatively correct only in CHARMM36. In all force fields, even the qualitatively correct responses were much exaggerated also in CHARMM36 that underestimated the Ca 2+ binding affinity-with the sole exception of the larger SαCH , whose change CHARMM36 underestimated._

New: _These responses were overestimated in simulations with all force fields with the sole exception of the larger SαCH in CHARMM36 simulation, whose change was underestimated. All of the responses were qualitatively correct only in CHARMM36, but the changes in SβCH and smaller SαCH were overestimated also in CHARMM36 simulations even thought **[should be: though]** the Ca2+ binding affinity was underestimated._

Proposed new: _In simulations, all of these responses were qualitatively correct only in CHARMM36. The only underestimated response in any simulation was seen in the larger SαCH with CHARMM36. All other responses were much exaggarated—also in CHARMM36 that underestimated the Ca2+ binding affinity._

**Comment by ohsOllila** [comment]
I have now updated to the "Proposed new" text.

**Comment by markussmiettinen** [comment]
I do not quite agree with the change on line 519, as I think it overly weakens our message.

Current: _Importantly, the experimentally measured responses of the PS headgroup SCH to bound calcium, as well as to dilution of the bilayer with zwitterionic PC lipids, were not qualitatively reproduced in any of the tested force fields._

New: _Importantly, the experimentally measured responses of the PS headgroup SCH to bound calcium, as well as to dilution of the bilayer with zwitterionic PC lipids, were not qualitatively reproduced in most of the tested force fields._

Proposed new: _Importantly, the experimentally measured responses of the PS headgroup SCH to bound calcium were qualitatively reproduced by just one—and the responses to dilution with zwitterionic PC lipids by none—of the tested force fields._

**Comment by ohsOllila** [comment]
I have now changed to the "Proposed new" sentence.
