### ISSUE TITLE
POPC vs OPPC simulations with MacRog

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#16]
During the project, it was [pointed out by @TomPiggot](http://nmrlipids.blogspot.com/2017/03/nmrlipids-iv-headgroup-glycerol.html?showComment=1513887245157#c9146940478822023431) that the available MacRog topology for POPS was actually OPPS. Therefore, all the results from MacRog simulations in the current manuscript are actually from POPC:OPPS mixtures. 

In addition,[ @TomPiggot prepared a correct itp file for MacRog POPS and reported the headgroup and glycerol backbone order parameters](http://nmrlipids.blogspot.com/2017/03/nmrlipids-iv-headgroup-glycerol.html?showComment=1524081965753#c5190176912574180774). When the results were [plotted together with the previous results from OPPS](https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/master/Figs/HGorderparametersPOPSvsOPPS-eps-converted-to.pdf), the difference was surprisingly large. However, the error bars are not there yet and I am not sure if the same ion models were used in these simulations.

Now, the question is that should we rerun the POPC:OPPS MacRog simulations using proper itp to make them POPC:POPS? My opinion is that this is not necessary. I believe that the conclusions would not change (PS headgroup order parameters in MacRog are not quite right, K+ binding is not overestimated, but Na+ and Ca2+ are). On the other hand, rerunning would make the manuscript more straightforward and the difference between POPS and OPPS, mentioned above, is little bit confusing.

Anyway, additional simulation of pure MacRog POPS (or OPPS, if the other systems are not reran) with only K+ counterions would be useful, for example, for [figure 8](https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/master/Figs/HGorderparametersPCvsPS-eps-converted-to.pdf).

**Comment by markussmiettinen** [comment]
Due to the mentioned reasons (making the manuscript more straightforward and avoiding confusion) I would support rerunning the simulations as POPC:POPS.

**Comment by mattijavanainen** [comment]
I agree with @markussmiettinen. @TomPiggot, could you please share the itp with me?

**Comment by TomPiggot** [comment]
I've sent @mattijavanainen the itp and it is also attached here as a zip.
[POPS_MacRog_fix-tail-order.zip](https://github.com/NMRLipids/NMRlipidsIVotherHGs/files/2184256/POPS_MacRog_fix-tail-order.zip)

This itp only has the tails switched around and shouldn't have anything else changed to the original topology (although I actually remade this one from scratch rather than manually modifying the old one). As mentioned on the blog, I think there probably should be some impropers included too although I did not do that so as to just be able to see the impact of the tail ordering.

Please feel free to share/modify/etc as you wish.

Cheers

Tom

**Comment by TomPiggot** [comment]
As for the sodium ions I used in the MacRog PS simulations, the parameters were the ones provided from:

https://www.sciencedirect.com/science/article/pii/S2352340916301755

**Comment by ohsOllila** [comment]
Maybe @TomPiggot or @mattijavanainen would have some insight in this: https://nmrlipids.blogspot.com/2018/07/nmrlipids-iv-first-draft-of-manuscript.html?showComment=1534158254048#c5715374048519851674

**Comment by ohsOllila** [comment]
I have now committed the results from new data by @mattijavanainen :
http://nmrlipids.blogspot.com/2018/07/nmrlipids-iv-first-draft-of-manuscript.html?showComment=1535364446749#c4563235956514366812

Commits are here:
https://github.com/NMRLipids/MATCH/commit/c2816aaea18e6e504575616813a5b5cc839cdbcf
https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/feeb2f0ebe28c4d98adcf93ffc3300363203ea84

When doing the analysis, I noticed another issue. The order parameters of POPC glycerol backbone in MacRog in the newer simulations are not the same as in older.
Older MacRog POPC, T310K used in NMRlipids I http://doi.org/10.5281/zenodo.13877 gives:
# OP_name    resname    atom1    atom2    OP_mean   OP_stddev  OP_stem
#--------------------------------------------------------------------
alpha2               POPC    CE    H2E    0.05694  0.05328  0.00471 
alpha1               POPC    CE    H1E    0.04324  0.04229  0.00374 
g2_1                 POPC    C13   H13   -0.19908  0.05349  0.00473 
g1_1                 POPC    C32   H322   0.01863  0.07034  0.00622 
g1_2                 POPC    C32   H321  -0.16120  0.05991  0.00530 
g3_2                 POPC    CF    H1F   -0.23531  0.04741  0.00419 
g3_1                 POPC    CF    H2f   -0.12542  0.06245  0.00552 
beta2                POPC    CD    H2D    0.03961  0.05852  0.00517 
beta1 POPC CD H1D 0.01316 0.04451 0.00393 


Newer MacRog POPC, T98K https://doi.org/10.5281/zenodo.1167531 gives:
# OP_name    resname    atom1    atom2    OP_mean   OP_stddev  OP_stem
#--------------------------------------------------------------------
alpha2               POPC    C5    H13    0.01614  0.13505  0.01194 
alpha1               POPC    C5    H12    0.02774  0.13320  0.01177 
g2_1                 POPC    C7    H16   -0.16545  0.19295  0.01705 
g1_1                 POPC    C10   H19    0.02189  0.33509  0.02962 
g1_2                 POPC    C10   H20    0.03532  0.25543  0.02258 
g3_2                 POPC    C6    H15   -0.07508  0.28718  0.02538 
g3_1                 POPC    C6    H14   -0.19893  0.19214  0.01698 
beta2                POPC    C1    H2    -0.00079  0.13679  0.01209 
beta1                POPC C1 H1 0.01047 0.13333 0.01178 

There seems to be similar issue in the simulations of mixtures. 

This is good to know, but I think that further study of this beyond the scope of NMRlipids IV, where we focus on PS lipids.

**Comment by ohsOllila** [comment]
Even thought it seems that there are still some unclarities between different MacRog files, I think that the issue related to the POPC vs. OPPS in the NMRlipids IV project is now clear. Thus, I will close this issue now.
