### ISSUE TITLE
Figure 2B

### ISSUE THREAD

**Issue by markussmiettinen** [NMRLipids/NMRlipidsIVotherHGs#34]
<s>1) Use diamonds for DOPS, spheres for POPS.</s>
  <s>2) Error bars?</s>
  <s>3) Change the y-label to $S_\mathrm{CH}$, and invert the y-axis, as in Fig. 3.</s>
  <s>4) Make lower g1 POPC visible, e.g., by slightly larger point.</s>

**Comment by ohsOllila** [comment]
I have updated this figure, also based on comments by Matti Javanainen in the blog. See new version pushed in this commit: https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/4368da5fcee99bbf5a291df176654ea6c3b9ca56

**Comment by hsantila** [comment]
It would be beneficial to replace the "literature" with "from Ref X"

**Comment by ohsOllila** [comment]
The original suggestions have been done. 

We can replace the "literature" with "from Ref X" just before submission when the  reference numbers are not changing anymore, I added a todo point about this into the manuscript.

**Comment by markussmiettinen** [comment]
Can't you use \citenum to add 'X' without knowing its final value?

**Comment by markussmiettinen** [comment]
Figure would be more readable, if there would be a slight shifts along x-direction of the points.

For example. Keep POPC as is, but change POPS with 0.05 units to left ($1+0.05) and DOPS 0.05 units to right.

**Comment by ohsOllila** [comment]
> Can't you use \citenum to add 'X' without knowing its final value?

I do not know how this could be done inside the figure?

**Comment by markussmiettinen** [comment]
> > Can't you use \citenum to add 'X' without knowing its final value?
> 
> I do not know how this could be done inside the figure?

I am sorry, did not realize it was in the figure.

**Comment by markussmiettinen** [comment]
When adding the final reference number, one might like to use the in pull request #122 provided plot for the panel (B), as it is shows the data without overlaps.

**Comment by markussmiettinen** [comment]
Ivan Gushcin commented by email the following:

**there is somehow a sodium (Na+) close to POPS in the panel (A)**

The Na+ should be removed while preparing the final version of the panel (B), as discussed above. At the same time, it would be good to

**align the panel (A) components on the right, such that the texts POPS and POPC would be on top of another, and the lipid chemical structures too.**

**Comment by ohsOllila** [comment]
Updated figure in commit https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/be69b1f531edd9d8d815b23f46df057de066deb5 and mentioned in  the author_corrections file: https://www.dropbox.com/s/f3wfqjiw25qwafq/Author_Corrections.odt?dl=0

**Comment by markussmiettinen** [comment]
The reference numbers were not added to the key of panel B. (**POPC ref 46** and **DOPS ref 7**). Was this on purpose or just forgotten? If the latter, I am happy to update the plot for 2B.

**Comment by ohsOllila** [comment]
If you update the plot now, I can change it.

**Comment by markussmiettinen** [comment]
> If you update the plot now, I can change it.

Ok. I do it now.

**Comment by markussmiettinen** [comment]
Done, see c064784.

**Comment by ohsOllila** [comment]
Figure is now updated.
