### ISSUE TITLE
Figure 5

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#38]
It is commented by Matti Javanainen in the blog comment that it should be Slipids, not Slipid in figure 5
https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/master/Figs/comparisonTablePS.pdf

I could not find the source file for this figure from the git.

**Comment by markussmiettinen** [comment]
Fix also:

+ color of Slipids was bluer in NRMlipids I
+ no need to repeat lipid names, once is enough
+ replace 'experiment' with 2H NMR and 13 C NMR

**Comment by ohsOllila** [comment]
https://github.com/NMRLipids/NMRlipidsIVotherHGs/issues/38#issuecomment-461032276 probably refers to figure 3 rather than figure 5?

**Comment by ohsOllila** [comment]
There is something wrong with some letters in the caption of figure 5. This probably arises from different text editors used or something like that. I am not sure what there should actually be.

**Comment by jsmaatta** [comment]
I did a small update on the Fig 5 caption. The M and F are now formatted just like in NMRlipids I. Alternate formatting could be {\textbf{\footnotesize F}} which makes the font bold and a tiny bit smaller. The bolded alternative looks a bit nicer but is more confusing for the reader as not all the letters in Fig 5 are in bold font.

**Comment by ohsOllila** [comment]
Lipid17 -> Lipid17 / ff99

Lipid17 -> Lipid17 / JC

**Comment by markussmiettinen** [comment]
I changed Slipid to Slipids in fa572b2, and the Lipid17 ion types were included in my pull request #112. I think we can close this issue.
