### ISSUE TITLE
Subjective ranking of force fields (current Fig. 6)

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#4]
The alpha carbon of CHARMM36-UA model is better than that of GROMOS-CKP2 in the plot of subjective ranking of force fields (current Fig. 6). However, when I look figure 5, this does not seem to be the case. I think that forking is roughly equally good in these models, but GROMOS-CKP2 values are slightly closer to the experimental values. 

I was also thinking that maybe we should remove the forking from the quality measure. Instead we could just measure the distance between simulations and experiments separately for lower and higher order parameters (in case where stereochemistry is not known, if known, then take it into account). If the forking is not ok, it should be also visible in this measure.

**Comment by markussmiettinen** [comment]
I agree that this is a problem. However, as a solution I suggest to sharpen the definition of the **magnitude** measurable, such that a given sweetspot can only be used once per quality assessment. Now, e.g., for C36-UA the upper alpha sweetspot is used for both hydrogens, as this gives the smallest penalty.

With a quick glance of the NMRlipids:I -paper, it seems that I in fact used this single-use convention also there (see e.g. the Slipid ranking on g1 there), but did not write it explicitly in the Methods in the Supplementary Information.

**Comment by markussmiettinen** [comment]
I looked carefully through the Figures 2 and 4 in the NMRlipids-1 -paper, and indeed, for the g1 carbon, which is the only one with clear forking for PC, I there have taken the single-use convention. Therefore, we should now apply this convention also for PS, whose both alpha and g1 fork.

**Comment by ohsOllila** [comment]
I think that this is pretty much fixed now. I will close this. We can reopen if needed.
