### ISSUE TITLE
Yellow color in figures

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRlipidsIVotherHGs#40]
@mattijavanainen commented in the blog about using yellow colors in the figures "Change yellow to orange or sth else more visible" 

Yellow colors for Lipid14/17 (#FFD300) are now inherited from figure 3 to the other figures, and originally probably from the NMRlipids I publication. Should we change this to something else throughout the manuscript? Should we compromise the consistency between different NMRlipids publications?

**Comment by markussmiettinen** [comment]
I strongly prefer keeping the plots consistent across NMRlipids publications.

**Comment by ohsOllila** [comment]
We will use the current colors then.
