### ISSUE TITLE
Figure 4

### ISSUE THREAD

**Issue by hsantila** [NMRLipids/NMRlipidsIVotherHGs#48]
The figure is not clear.
1) A) has title CHARMM36 as a title on the overlayed conformations, while B) has titles POPS and POPC. I would keep this consistent
2) The caption beginning implies that conformations are from CHARMM36 but the caption end refers to Slipids trajectory

**Comment by ohsOllila** [comment]
Figure and caption updated. If there are no further comments, we can close this.

**Comment by ohsOllila** [comment]
I will close this for clarity, please reopen if there are further comments.
