### ISSUE TITLE
Figure 10/Figure S18

### ISSUE THREAD

**Issue by hsantila** [NMRLipids/NMRlipidsIVotherHGs#69]
The caption in figure 10 claims that these are the smallest simulated concentrations. For C36 this is 260mM. However, figure S18 label says there is a C36 simulation with 150mM. This might be a typo since Table II does not mention C36 simulation with 150mM

**Comment by ohsOllila** [comment]
This was a typo, now fixed in here: https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/7fd673f87bd27e347e478a9498db370001878ab5
