### ISSUE TITLE
Small changes to text of the manuscript

### ISSUE THREAD

**Issue by jmelcr** [NMRLipids/NMRlipidsIVotherHGs#99]
In the following line,

https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/82bd450f12698f7cfa5148cc8fdc78b52479ccd0/Manuscript/manuscriptPS.tex#L161

I would rather state:
>' It is also suggested in some studies that ... '
resp.
' In some studies, it is also suggested that ... '

In the following line,

https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/82bd450f12698f7cfa5148cc8fdc78b52479ccd0/Manuscript/manuscriptPS.tex#L415

it is not immediately clear, what is the "former definition", because it appears three sentences before. I would rather state the definition, probably like 
>' In this work we use the former definition, i.e., concentration before solvating the lipids, to be consistent ... '

or put it into brackets. 

In the line

https://github.com/NMRLipids/NMRlipidsIVotherHGs/blob/82bd450f12698f7cfa5148cc8fdc78b52479ccd0/Manuscript/manuscriptPS.tex#L547

I would add the information that
>' Only one of the two Ogamma atoms in the carboxylate group from PS lipids is shown for clarity. '

before the sentence "The trajectory ..."
Following the discussion in issue #94 .

**Comment by ohsOllila** [comment]
The first suggestion I did not understand. The second and third are included in the commit https://github.com/NMRLipids/NMRlipidsIVotherHGs/commit/10c875308f5de60e95ef4fce09d254b3b3bc385b. However, the third I put in the caption in the SI because caption in the figure in the main text is already quite long.
